name: Build workshop docs
on:
  push:
    branches: [main]

jobs:
  docs:
    name: Build docs
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install tools
        run: npm i -g @moaw/cli
      - name: Build and update docs
        run: |
          git config --global user.name "sinedied"
          git config --global user.email "noda@free.fr"
          ./scripts/repo/build-docs.sh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

